# Generated by Django 5.0.2 on 2024-08-05 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0005_alter_videofile_video_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('model', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('qty_planned', models.IntegerField()),
                ('qty_actual', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screen_app.unit')),
            ],
            options={
                'verbose_name': 'Daily Production Plan Vs Actual LineWise',
                'verbose_name_plural': 'Daily Production Plan Vs Actual Total LineWise',
            },
        ),
        migrations.CreateModel(
            name='DailyProductionPlan',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('qty_planned', models.IntegerField()),
                ('qty_actual', models.IntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='screen_app.unit')),
            ],
            options={
                'verbose_name': 'Daily Production Plan Vs Actual Total',
                'verbose_name_plural': 'Daily Production Plan Vs Actual Total',
                'ordering': ['date', 's_no'],
            },
        ),
    ]
