# Generated by Django 5.0.2 on 2024-08-08 10:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0006_unit_productionplan_dailyproductionplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(default='Image_Name', help_text='Name of Image file', max_length=100)),
                ('image_file', models.ImageField(help_text='Upload PNG or JPG image', upload_to='static/media/Images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='screen',
            name='upload_images',
            field=models.ManyToManyField(blank=True, to='screen_app.images'),
        ),
    ]
