# Generated by Django 5.0.2 on 2024-08-10 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0007_images_screen_upload_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image_duration',
            field=models.IntegerField(default=20, help_text='Duration of Image in seconds'),
        ),
    ]
