# Generated by Django 5.0.2 on 2024-08-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0008_images_image_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='images',
            name='image_duration',
            field=models.IntegerField(default=20, help_text='Duration in seconds (positive integer)'),
        ),
    ]
