# Generated by Django 5.0.2 on 2024-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0009_alter_images_options_alter_images_image_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AssebmlyLine-1', max_length=200, unique=True)),
            ],
        ),
    ]
