# Generated by Django 5.0.2 on 2024-08-13 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0010_assemblyline'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproductionplan',
            name='assembly_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='screen_app.assemblyline'),
            preserve_default=False,
        ),
    ]
