# Generated by Django 5.0.2 on 2024-08-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0012_alter_dailyproductionplan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyline',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
