# Generated by Django 5.0.2 on 2024-08-14 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0013_assemblyline_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblyline',
            name='number',
        ),
    ]
