# Generated by Django 5.0.2 on 2024-08-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_app', '0014_remove_assemblyline_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyline',
            name='number',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assemblyline',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyproductionplan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
