# Generated by Django 5.0.6 on 2024-08-23 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0017_alter_dailyproductionplan_qty_actual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyProductionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="DailyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("quantity", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.unit",
                    ),
                ),
                (
                    "weekly_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="screen_app.weeklyproductionplan",
                    ),
                ),
            ],
            options={
                "unique_together": {("weekly_plan", "date")},
            },
        ),
    ]
