# Generated by Django 5.1 on 2024-08-26 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0019_alter_screen_manager_alter_screen_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="product",
            field=models.ForeignKey(
                blank=True,
                default="Trans ACNR",
                on_delete=django.db.models.deletion.CASCADE,
                to="screen_app.product",
            ),
        ),
    ]
