# Generated by Django 5.1 on 2024-08-26 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0020_alter_screen_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="upload_pdf",
        ),
    ]
