# Generated by Django 5.1 on 2024-08-27 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0022_productionplantotal"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together={("weekly_plan",)},
        ),
        migrations.AlterField(
            model_name="dailyplan",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
