# Generated by Django 5.1 on 2024-08-27 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "screen_app",
            "0024_alter_dailyplan_unique_together_alter_dailyplan_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together={("weekly_plan",)},
        ),
    ]
