# Generated by Django 5.1 on 2024-08-27 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0025_alter_dailyplan_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailyplan",
            options={"verbose_name": "Daily plans for weekly production"},
        ),
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together=set(),
        ),
    ]
