# Generated by Django 5.1 on 2024-08-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0026_alter_dailyplan_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dailyplan",
            unique_together={("unit",)},
        ),
    ]
