# Generated by Django 5.1 on 2024-08-29 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0029_unitmedia"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitmedia",
            name="file",
            field=models.FileField(
                upload_to="unit_media/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "mp4", "mov", "zip"]
                    )
                ],
            ),
        ),
    ]
