# Generated by Django 5.1 on 2024-08-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0030_alter_unitmedia_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="product",
        ),
    ]
