# Generated by Django 5.1 on 2024-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0032_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
