# Generated by Django 5.1 on 2024-09-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0033_station_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="station",
            name="content",
        ),
        migrations.AddField(
            model_name="station",
            name="selected_media",
            field=models.ManyToManyField(
                blank=True, related_name="stations", to="screen_app.unitmedia"
            ),
        ),
        migrations.AddField(
            model_name="unitmedia",
            name="duration",
            field=models.PositiveIntegerField(blank=True, default=30),
        ),
    ]
