# Generated by Django 5.1 on 2024-09-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("screen_app", "0034_remove_station_content_station_selected_media_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productionplan",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
